### ISSUE TITLE
Fiducial Parameters.vi pointing to wrong directory for find_rects_parameters.ctl within gVision

### ISSUE THREAD

**Issue by souvik1982** [CUASAS/pixel-gantry-control#18]
![Capture_PathNeeds Fixing](https://user-images.githubusercontent.com/5023891/108802760-01f75600-7567-11eb-8d18-05fbe8ae01f5.PNG)

**Comment by rishabhCMS** [comment]
@souvik1982 
I guess we had a similar issue, which was solved by renaming the gVision.-.v1.3 -> gVision API

**Comment by cfangmeier** [comment]
@rishabhCMS, that is exactly the solution. I updated the README to be more explicit about how to install gVision and added an empty folder into the git repo called `gVision API`.
