### ISSUE TITLE
AUTOFOCUS error

### ISSUE THREAD

**Issue by gopchang24** [CUASAS/pixel-gantry-control#37]
Hi!
 I found a bug of the AUTOFOCUS function.
 When I run the function, the scan (drawing gaussian distribution) works well.
 But the measured height, which means the peak location of the gaussian, is wrong.
 The height is the lower or upper boundary of the scanning range as shown in the attached file.
 This happened occasionally.
 Would you check it?

![AUTOFOCUS_fit](https://user-images.githubusercontent.com/53192949/132563243-de1fe731-8fe0-41c2-80de-98a982337560.PNG)

**Comment by cfangmeier** [comment]
Hi @gopchang24 . Is this reproducible? Meaning, if you run the same autofocus while looking at the same spot, does it do this every time?

**Comment by gopchang24** [comment]
I didn't do the reproducible study,
but it seems like the result is the same when I run the AUTOFOCUS at the
same initial position
although the output is correct or not.

-- 

Cheers,
Changwoo Joo

***@***.***
Univ. of Nebraska-Lincoln, Dept. of Physics, JH 208,
855 N 16th St., Lincoln, NE, 68588-0299, USA

**Comment by cfangmeier** [comment]
Closing this pending reproducibility.
