### ISSUE TITLE
Migrate site-specific configurations out of this repository

### ISSUE THREAD

**Issue by cfangmeier** [CUASAS/pixel-gantry-control#68]
As more sites start regularly using gScript, it's quickly becoming a bottleneck for everyone to commit changes to their `flex_config`s or gScript files and submit PRs to this repository. 

At some point over the next few weeks, the `Config/` and `Scripts/` directories will be cleared out. I'll leave a minimalistic example `flex_config.txt` and some example gScript files. (Everything that currently exists will still be there in the git history so nobody panic)

From that point forward individual sites/projects will need to be responsible for their own configurations and scripts. I'll add a section to the readme with relevant links to help people know where to find the files for their specific work.

As we work through this transition at UNL, I'll update this thread with recommended best-practices on how to organize files outside this repository.

**Comment by souvik1982** [comment]
Should we migrate all our Config and Scripts to an independent repository dedicated to TFPX Modules Assembly? I can create and maintain one for all of us.

**Comment by cfangmeier** [comment]
Yes, that's a good start. I'm currently reworking some of the logic dealing with paths for config files, scripts and logs. My current approach is for the user to specify a directory somewhere on their computer that contains the `Logs`, `Config`, and `Scripts` subdirectories. If this isn't specified in the ini file, a normal directory selection dialog will pop-up. This "project directory" can itself be tracked in git however a site likes, for example using git submodules to bring in project-wide scripts.

Along those same lines, I'd encourage you to look for any entries in the flex_config that are not site specific and migrate them out of the `flex_config` and put them in a new config file (can be named anything) side by side with the scripts that need that configuration. This data can then be loaded with a `LOADCONFIG` in the scripts that need them, but won't pollute the sites `flex_config`.

**Comment by cfangmeier** [comment]
I just pushed a commit removing site-specific scripts and configuration files. Each site should now create a repository for their own setup. Nebraska's is [here](https://github.com/nebraska-silicon-lab/gantry-config-nebraska). It contains the Nebraska `flex_config.txt` and Nebraska-specific scripts. This first repository is a "Project Directory". One uses it by cloning it somewhere separate from gScript itself. Then, when starting gScript for the first time there will be a prompt asking for the location of this directory. This choice is remembered upon subsequent launches.

I created a 2nd repository for project-wide scripts for [ETL](https://github.com/nebraska-silicon-lab/gscript-ETLModules/tree/4c3f15f21a489785e8a5aba525b311b95af8d16d) that is added as a submodule in the 1st repo.

@souvik1982 , I suggest you follow the same pattern for Purdue/TFPX by creating 2 new repositories: one called `gantry-config-purdue` that follows the layout of `gantry-config-nebraska` and a 2nd called `gscript-TFPXModules` that contains the files that were [previously in Scripts/TFPXModules](https://github.com/CUASAS/pixel-gantry-control/tree/915881a76ddb3a5ce81e0f5fd879252420630516/Scripts/TFPXModules). You can then add this shared repository as a git submodule in `gantry-config-purdue` using something like: 

`git submodule add git@github.com:souvik1982/gscript-TFPXModules.git Scripts/TFPXModules`

Finally, these changes work on my development machine, but haven't been thoroughly tested yet. As such, I suggest all sites that want to update make a fresh clone of `pixel-gantry-control` and make sure that it works before removing their existing install.
