### ISSUE TITLE
Add ability to run FINDFID on composite images

### ISSUE THREAD

**Issue by cfangmeier** [CUASAS/pixel-gantry-control#79]
Currently the pattern recognition command, FINDFID, can only run on a single image taken with the camera. This can lead to an issue where if the fiducial pattern is larger than the camera's field-of-view then it cannot be captured in a single image. The solution is to allow for multiple images to be stitched together first followed by the pattern recognition step. This logic is already developed for the SURVEY command. It just has to be hooked up to the FINDFID command. 

To specify the size of the extended field-of-view, new (optional) entries will be added to the fiducial specification. e.g.

```
vision.example2.method: find_rects
vision.example2.scan_window_x: 5  # mm
vision.example2.scan_window_y: 3  # mm
```

**Comment by cfangmeier** [comment]
The current implementation fails with non-standard camera orientation. Need to update the image stitching portion of the code to take into account that the +x axis does not always point to the right in the acquired images.

**Comment by cfangmeier** [comment]
Fantastic! It's difficult to test so I wasn't sure the implementation would actually work :smile:.

**Comment by shoogend** [comment]
Haha yes I can imagine!
