### ISSUE TITLE
POTLINE and POTDOT simpler functionality

### ISSUE THREAD

**Issue by shoogend** [CUASAS/pixel-gantry-control#81]
Hi Caleb,

I am attempting to use the POTLINE and POTDOT commands with our Nordson Ultimus II dispenser setup. Ideally, all I need is a command to turn on and off the dispenser (we are dispensing a thermal grease). The POTLINE and POTDOT commands have additionally functionality built in that I do not need (such as variables for curing time, needing to load a syringe tool, syringe state, etc). Is there a way to create a simpler function to just turn on and off the dispenser? Thank you!

**Comment by cfangmeier** [comment]
I'll have a look at what can be done to simplify the operation later this week. In the meantime, you should be able to hack it by pretending the output controlling the dispenser is a vacuum line and using the setvac command.

**Comment by shoogend** [comment]
Sounds good. I will use that in the meantime.

**Comment by cfangmeier** [comment]
I just pushed a new command `SETDISPENSE` which should meet your needs. Just turn the dispenser on/off with

```
SETDISPENSE 1
SETDISPENSE 0
```

You do still need to "load" the syringe though, but if there is no syringe in the tool rack (meaning it's more or less permanently on the gantry head), you can just do `LOADTOOL syringe_tool` and the software will just register the tool is loaded and take no further action. So, a full (very simple) script might look like:

```
LOADTOOL syringe_tool  # no motion. just changing the "loaded" tool in memory
MOVETO {123,345,123}  # or wherever
SETDISPENSE 1
WAIT 1000
SETDISPENSE 0
UNLOADTOOL  # again, no motion.
```

**Comment by shoogend** [comment]
Thank you - looks great. One question, for the flex_config file I assume we need a setup similar to the manifold.* and/or vacuum.* namespaces? Could you show an example of what that should look like as well?

**Comment by cfangmeier** [comment]
The setup for the dispenser is simpler, without needed the extra layer of redirection that the vacuum lines use. New documentation added here:

https://github.com/CUASAS/pixel-gantry-control/blob/master/Example%20Project/Config/flex_config.txt#L84-L86

And if the new changes are working for you, please go ahead and close the issue.
