### ISSUE TITLE
SETDISPENSE issue

### ISSUE THREAD

**Issue by shoogend** [CUASAS/pixel-gantry-control#82]
Occasionally, the following error occurs:
![image](https://github.com/CUASAS/pixel-gantry-control/assets/80776778/996b4af4-c561-4763-a0b7-59b9bd20fa72)
I noticed this is reproducible if I first call VIDEO on one line and the next line try to use SETDISPENSE. I am not sure why this causes this error.

On the other hand, sometimes no error message occurs but SETDISPENSE simply does not turn on the dispenser. In order to get it to work, I usually close gScript, open NI Max and test the dispenser by turning it on and off with the test panels (which always works), reopen gScript, and retry the code/command (which usually fixes the issue).

In both cases, the command is not functioning entirely as expected. Please let me know if any other information would be useful.

**Comment by cfangmeier** [comment]
According to LabVIEW, that error code means:

> The specified operation cannot be performed because a task has been aborted or a device has been removed from the system. Handle this situation as required by the application and then, if appropriate, attempt to perform the operation again.

I wonder if somehow the USB line is being contested by the camera and the CompactDAQ. If you just put a short delay (say 100ms) between video and setdispense, does that eliminate the problem? Also, how are the camera and CompactDAQ physically connected to the PC. Are they on separate ports? Using a hub?

**Comment by shoogend** [comment]
We have a USB hub connected to the PC. The camera is directly plugged into this hub and the dispenser connects to the cDAQ which is then also connected via USB to this hub. 

I tried adding the delay but this did not fix it. This is the procedure I used:

First, I ran this code to ensure the dispenser was working:
`LOADTOOL syringe_tool
SETDISPENSE 1
WAIT 100
SETDISPENSE 0
UNLOADTOOL syringe_tool`

This functioned as expected. Then I ran the following code:
`LOADTOOL syringe_tool
VIDEO
WAIT 1000
SETDISPENSE 1
WAIT 100
SETDISPENSE 0
UNLOADTOOL syringe_tool`

which gave the error (same I posted initially):

> Line 4 "SETDISPENSE 1"
Code: -88709
Gantry.lvclass:Set Dispenser State.vi<append>
<B>Task Name: </B>Dispenser IO Task

If I then try to rerun the first block of code (without the video command). The  "SETDISPENSE 1" command no longer works (i.e. the dispenser does not turn on). Howeverk, this does not produce any error message.

**Comment by cfangmeier** [comment]
Another couple questions: Is the camera drawing all of it's power from the USB? And is the USB hub externally powered? 

I wonder if when the camera turns on, if it momentarily interrupts the connection with the cDAQ which breaks the labview DAQmx task. I'd like you to try plugging the camera into a different port on the PC and see if that changes anything.

**Comment by shoogend** [comment]
Yes I believe the camera is drawing all of its power from the USB. And I do not think the USB hub is externally powered- it is itself connected via USB to a port on the back of the PC.

I tried plugging the camera into a different port on the PC and this seemed to resolve the issue with the error above. However, I do notice that the camera will lag significantly with some ports on the back of the PC vs. others. I rearranged some of our devices and have seem to come up with an arrangement that allows the hub to be on one port and the camera on another on the back of the PC so that it will not lag. Is there any reason you can think of for this lagging with one of the specific ports?

**Comment by cfangmeier** [comment]
> Is there any reason you can think of for this lagging with one of the specific ports?

Is your camera USB 3? Maybe some of the ports are just USB 2. Or 1 if you are using an ancient PC for your gantry controller. Does the camera still lag on those ports if you use the native uEye Cockpit application, or just when using gScript?

**Comment by shoogend** [comment]
I am again getting an issue with the SETDISPENSE command. Whenever I first try to use gScript and execute the commands
```
LOADTOOL syringe_tool
SETDISPENSE 1
```
nothing happens with the dispenser -- i.e. it does not turn on but there is no error message either. To fix this, I use NI MAX and its the test panels to manually open and close the dispenser (turn it on and off) and then go back to gScript. If I then rerun the above commands, it works as expected. Do you know why it may not be working on the first attempt? All the port issues we discussed last time should still be the same. So there should not be any conflicts there.
