### ISSUE TITLE
DIALOG add images

### ISSUE THREAD

**Issue by shoogend** [CUASAS/pixel-gantry-control#84]
Could we potentially add functionality to the DIALOG command so that we can show an image in the popup box? I am using some of the DIALOG boxes to instruct the user of the code to perform a certain action and being able to include an image as part of the instructions would be very helpful.

**Comment by cfangmeier** [comment]
This should be doable. Can you provide an example mockup of what you are looking for so that I can make sure whatever I implement can fit your needs?

**Comment by shoogend** [comment]
Of course. Here is an example mockup:
![image](https://github.com/CUASAS/pixel-gantry-control/assets/80776778/ffc7b271-5ce0-46f9-ad42-54c1c25ae4f4)

All I need is to be able to insert an image into the dialog box to reference when I give an instruction to the user.

**Comment by cfangmeier** [comment]
I have a working implementation. The dialog config and result are shown below.

```ini
[window]
width=300
height=450
title=Test Dialog

[float_input_1]
label=Hello World
x=10
y=120
default=16.12
variable="$float1"

[int_input_2]
label=Hello World
x=110
y=120
default=16
variable="$int2"

[bool_input_1]
label=Boolean input 1
x=10
y=10
default=false
variable=$bool1

[bool_input_2]
label=Boolean input 2
x=110
y=10
default=true
variable=$bool2

[picture_1]
label=Cat
path=C:\Users\cfang\Desktop\2569566.jpg
x=50
y=170
width=200
height=200
```

![image](https://github.com/CUASAS/pixel-gantry-control/assets/2569566/17497b45-595f-40af-baa1-7c248228a548)

It's currently not possible to separately add a text box with instructions, but I think it's reasonable to just embed any necessary instructions into the image. Currently I'm only supporting up to 2 images in one dialog. Is that enough or should I add more?

In any case, I'll push out a new release this week with this feature added.

**Comment by shoogend** [comment]
Yes this looks great. 2 images in one dialog is perfect. Thank you!

**Comment by cfangmeier** [comment]
Ok. Go ahead and try out the latest release which includes this feature. Please feel free to re-open the issue if it's not working for you.
