### ISSUE TITLE
Circular motion command request

### ISSUE THREAD

**Issue by shoogend** [CUASAS/pixel-gantry-control#85]
Could a command be created so that a circular motion of a certain radius and speed and at a certain position can be performed by the gantry? I believe LabVIEW already has a built-in command like this and it would be helpful for specific actions.

**Comment by cfangmeier** [comment]
I added a `MOVECIR` command. I'll update the docs shortly, but essentially you run it like this:

```
MOVECIR $dest $radius cw/ccw $speed
```

which should move from the current position to `$dest` along a circular path in the x-y plane of `$radius`, going either clockwise (`cw`) or counter-clockwise (`ccw`) at `$speed` mm/s. There should be no movement along the z-axis, even if `$dest.z` is different than the current z coordinate.

Note I don't currently have access to a gantry that I can test this on so take precautions when try this out in case there is any unexpected motion.

**Comment by shoogend** [comment]
Great - thank you. Sounds good, I will be careful!
